-- ========================================
-- 사용자 (소유자 식별용)
-- ========================================
CREATE TABLE resume.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_key VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_user_key UNIQUE (user_key)
);
COMMENT ON TABLE resume.users IS '사용자 정보';
COMMENT ON COLUMN resume.users.user_id IS '사용자 PK';
COMMENT ON COLUMN resume.users.user_key IS '외부에서 전달되는 사용자 식별값';
COMMENT ON COLUMN resume.users.created_at IS '생성일시';
COMMENT ON COLUMN resume.users.updated_at IS '수정일시';
-- ========================================
-- 이력서
-- ========================================
CREATE TABLE resume.resumes (
    resume_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    template_id BIGINT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_resumes PRIMARY KEY (resume_id)
);
COMMENT ON TABLE resume.resumes IS '이력서 정보';
COMMENT ON COLUMN resume.resumes.resume_id IS '이력서 PK';
COMMENT ON COLUMN resume.resumes.user_id IS '사용자 ID';
COMMENT ON COLUMN resume.resumes.title IS '이력서 제목';
COMMENT ON COLUMN resume.resumes.template_id IS '적용 템플릿 ID';
COMMENT ON COLUMN resume.resumes.created_at IS '생성일시';
COMMENT ON COLUMN resume.resumes.updated_at IS '수정일시';
-- ========================================
-- 기본 정보
-- ========================================
CREATE TABLE resume.resume_profile (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resume_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(30),
    address VARCHAR(255),
    profile_image VARCHAR(255),
    birth_date DATE,
    introduction TEXT,
    CONSTRAINT pk_resume_profile PRIMARY KEY (profile_id)
);
COMMENT ON TABLE resume.resume_profile IS '이력서 기본 정보';
COMMENT ON COLUMN resume.resume_profile.profile_id IS '기본 정보 PK';
COMMENT ON COLUMN resume.resume_profile.resume_id IS '이력서 ID';
COMMENT ON COLUMN resume.resume_profile.name IS '이름';
COMMENT ON COLUMN resume.resume_profile.email IS '이메일';
COMMENT ON COLUMN resume.resume_profile.phone IS '전화번호';
COMMENT ON COLUMN resume.resume_profile.address IS '주소';
COMMENT ON COLUMN resume.resume_profile.profile_image IS '프로필 이미지 경로 또는 URL';
COMMENT ON COLUMN resume.resume_profile.birth_date IS '생년월일';
COMMENT ON COLUMN resume.resume_profile.introduction IS '자기소개';
-- ========================================
-- 외부 링크
-- ========================================
CREATE TABLE resume.resume_link (
    link_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resume_id BIGINT NOT NULL,
    link_type VARCHAR(50) NOT NULL,
    display_name VARCHAR(100),
    url VARCHAR(255) NOT NULL,
    sort_order INTEGER DEFAULT 0,
    CONSTRAINT pk_resume_link PRIMARY KEY (link_id)
);
COMMENT ON TABLE resume.resume_link IS '이력서 외부 링크';
COMMENT ON COLUMN resume.resume_link.link_id IS '링크 PK';
COMMENT ON COLUMN resume.resume_link.resume_id IS '이력서 ID';
COMMENT ON COLUMN resume.resume_link.link_type IS '링크 유형(github, linkedin, blog, portfolio, website 등)';
COMMENT ON COLUMN resume.resume_link.display_name IS '화면 표시 이름';
COMMENT ON COLUMN resume.resume_link.url IS '링크 URL';
COMMENT ON COLUMN resume.resume_link.sort_order IS '출력 순서';
-- ========================================
-- 경력
-- ========================================
CREATE TABLE resume.resume_experience (
    experience_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resume_id BIGINT NOT NULL,
    company_name VARCHAR(100) NOT NULL,
    position VARCHAR(100) NOT NULL,
    start_date DATE,
    end_date DATE,
    is_current BOOLEAN DEFAULT FALSE,
    description TEXT,
    sort_order INTEGER DEFAULT 0,
    CONSTRAINT pk_resume_experience PRIMARY KEY (experience_id)
);
COMMENT ON TABLE resume.resume_experience IS '이력서 경력 정보';
COMMENT ON COLUMN resume.resume_experience.experience_id IS '경력 PK';
COMMENT ON COLUMN resume.resume_experience.resume_id IS '이력서 ID';
COMMENT ON COLUMN resume.resume_experience.company_name IS '회사명';
COMMENT ON COLUMN resume.resume_experience.position IS '직책';
COMMENT ON COLUMN resume.resume_experience.start_date IS '시작일';
COMMENT ON COLUMN resume.resume_experience.end_date IS '종료일';
COMMENT ON COLUMN resume.resume_experience.is_current IS '재직 여부';
COMMENT ON COLUMN resume.resume_experience.description IS '경력 설명';
COMMENT ON COLUMN resume.resume_experience.sort_order IS '출력 순서';
-- ========================================
-- 프로젝트
-- ========================================
CREATE TABLE resume.resume_project (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resume_id BIGINT NOT NULL,
    project_name VARCHAR(150) NOT NULL,
    start_date DATE,
    end_date DATE,
    description TEXT,
    role VARCHAR(100),
    tech_stack TEXT,
    github_url VARCHAR(255),
    demo_url VARCHAR(255),
    sort_order INTEGER DEFAULT 0,
    CONSTRAINT pk_resume_project PRIMARY KEY (project_id)
);
COMMENT ON TABLE resume.resume_project IS '이력서 프로젝트 정보';
COMMENT ON COLUMN resume.resume_project.project_id IS '프로젝트 PK';
COMMENT ON COLUMN resume.resume_project.resume_id IS '이력서 ID';
COMMENT ON COLUMN resume.resume_project.project_name IS '프로젝트명';
COMMENT ON COLUMN resume.resume_project.start_date IS '시작일';
COMMENT ON COLUMN resume.resume_project.end_date IS '종료일';
COMMENT ON COLUMN resume.resume_project.description IS '프로젝트 설명';
COMMENT ON COLUMN resume.resume_project.role IS '담당 역할';
COMMENT ON COLUMN resume.resume_project.tech_stack IS '사용 기술 스택';
COMMENT ON COLUMN resume.resume_project.github_url IS 'GitHub URL';
COMMENT ON COLUMN resume.resume_project.demo_url IS '데모 URL';
COMMENT ON COLUMN resume.resume_project.sort_order IS '출력 순서';
-- ========================================
-- 학력
-- ========================================
CREATE TABLE resume.resume_education (
    education_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resume_id BIGINT NOT NULL,
    school_name VARCHAR(150) NOT NULL,
    major VARCHAR(150),
    degree VARCHAR(100),
    start_date DATE,
    end_date DATE,
    description TEXT,
    sort_order INTEGER DEFAULT 0,
    CONSTRAINT pk_resume_education PRIMARY KEY (education_id)
);
COMMENT ON TABLE resume.resume_education IS '이력서 학력 정보';
COMMENT ON COLUMN resume.resume_education.education_id IS '학력 PK';
COMMENT ON COLUMN resume.resume_education.resume_id IS '이력서 ID';
COMMENT ON COLUMN resume.resume_education.school_name IS '학교명';
COMMENT ON COLUMN resume.resume_education.major IS '전공';
COMMENT ON COLUMN resume.resume_education.degree IS '학위';
COMMENT ON COLUMN resume.resume_education.start_date IS '입학일';
COMMENT ON COLUMN resume.resume_education.end_date IS '졸업일';
COMMENT ON COLUMN resume.resume_education.description IS '학력 설명';
COMMENT ON COLUMN resume.resume_education.sort_order IS '출력 순서';
-- ========================================
-- 기술 스택
-- ========================================
CREATE TABLE resume.resume_skill (
    skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resume_id BIGINT NOT NULL,
    skill_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    proficiency SMALLINT,
    sort_order INTEGER DEFAULT 0,
    CONSTRAINT pk_resume_skill PRIMARY KEY (skill_id)
);
COMMENT ON TABLE resume.resume_skill IS '이력서 기술 스택';
COMMENT ON COLUMN resume.resume_skill.skill_id IS '기술 스택 PK';
COMMENT ON COLUMN resume.resume_skill.resume_id IS '이력서 ID';
COMMENT ON COLUMN resume.resume_skill.skill_name IS '기술명';
COMMENT ON COLUMN resume.resume_skill.category IS '기술 분류';
COMMENT ON COLUMN resume.resume_skill.proficiency IS '숙련도';
COMMENT ON COLUMN resume.resume_skill.sort_order IS '출력 순서';
-- ========================================
-- 자격증
-- ========================================
CREATE TABLE resume.resume_certificate (
    certificate_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resume_id BIGINT NOT NULL,
    certificate_name VARCHAR(150) NOT NULL,
    issuer VARCHAR(150),
    issued_date DATE,
    description TEXT,
    sort_order INTEGER DEFAULT 0,
    CONSTRAINT pk_resume_certificate PRIMARY KEY (certificate_id)
);
COMMENT ON TABLE resume.resume_certificate IS '이력서 자격증 정보';
COMMENT ON COLUMN resume.resume_certificate.certificate_id IS '자격증 PK';
COMMENT ON COLUMN resume.resume_certificate.resume_id IS '이력서 ID';
COMMENT ON COLUMN resume.resume_certificate.certificate_name IS '자격증명';
COMMENT ON COLUMN resume.resume_certificate.issuer IS '발급 기관';
COMMENT ON COLUMN resume.resume_certificate.issued_date IS '취득일';
COMMENT ON COLUMN resume.resume_certificate.description IS '자격증 설명';
COMMENT ON COLUMN resume.resume_certificate.sort_order IS '출력 순서';
-- ========================================
-- 템플릿
-- ========================================
CREATE TABLE resume.templates (
    template_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_name VARCHAR(100) NOT NULL,
    description TEXT,
    thumbnail_url VARCHAR(255),
    html_content TEXT NOT NULL,
    css_content TEXT,
    is_public BOOLEAN DEFAULT TRUE,
    created_by BIGINT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_templates PRIMARY KEY (template_id)
);
COMMENT ON TABLE resume.templates IS '이력서 템플릿';
COMMENT ON COLUMN resume.templates.template_id IS '템플릿 PK';
COMMENT ON COLUMN resume.templates.template_name IS '템플릿 이름';
COMMENT ON COLUMN resume.templates.description IS '템플릿 설명';
COMMENT ON COLUMN resume.templates.thumbnail_url IS '썸네일 이미지 URL';
COMMENT ON COLUMN resume.templates.html_content IS 'HTML 템플릿 내용';
COMMENT ON COLUMN resume.templates.css_content IS 'CSS 스타일 내용';
COMMENT ON COLUMN resume.templates.is_public IS '공개 여부';
COMMENT ON COLUMN resume.templates.created_by IS '생성 사용자 ID';
COMMENT ON COLUMN resume.templates.created_at IS '생성일시';
COMMENT ON COLUMN resume.templates.updated_at IS '수정일시';
-- ========================================
-- 템플릿 섹션 배치
-- ========================================
CREATE TABLE resume.template_section (
    section_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_id BIGINT NOT NULL,
    section_type VARCHAR(50) NOT NULL,
    display_name VARCHAR(100),
    position_x INTEGER DEFAULT 0,
    position_y INTEGER DEFAULT 0,
    width INTEGER DEFAULT 12,
    height INTEGER DEFAULT 1,
    sort_order INTEGER DEFAULT 0,
    visible BOOLEAN DEFAULT TRUE,
    style_json JSONB,
    CONSTRAINT pk_template_section PRIMARY KEY (section_id)
);
COMMENT ON TABLE resume.template_section IS '템플릿 섹션 배치 정보';
COMMENT ON COLUMN resume.template_section.section_id IS '섹션 PK';
COMMENT ON COLUMN resume.template_section.template_id IS '템플릿 ID';
COMMENT ON COLUMN resume.template_section.section_type IS '섹션 유형(profile, project, experience 등)';
COMMENT ON COLUMN resume.template_section.display_name IS '화면 표시 이름';
COMMENT ON COLUMN resume.template_section.position_x IS 'X 좌표';
COMMENT ON COLUMN resume.template_section.position_y IS 'Y 좌표';
COMMENT ON COLUMN resume.template_section.width IS '너비';
COMMENT ON COLUMN resume.template_section.height IS '높이';
COMMENT ON COLUMN resume.template_section.sort_order IS '출력 순서';
COMMENT ON COLUMN resume.template_section.visible IS '노출 여부';
COMMENT ON COLUMN resume.template_section.style_json IS '섹션 스타일 JSON';
-- ========================================
-- PDF 생성 이력
-- ========================================
CREATE TABLE resume.resume_pdf (
    pdf_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resume_id BIGINT NOT NULL,
    template_id BIGINT NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_resume_pdf PRIMARY KEY (pdf_id)
);
COMMENT ON TABLE resume.resume_pdf IS 'PDF 생성 이력';
COMMENT ON COLUMN resume.resume_pdf.pdf_id IS 'PDF PK';
COMMENT ON COLUMN resume.resume_pdf.resume_id IS '이력서 ID';
COMMENT ON COLUMN resume.resume_pdf.template_id IS '템플릿 ID';
COMMENT ON COLUMN resume.resume_pdf.file_path IS '파일 저장 경로';
COMMENT ON COLUMN resume.resume_pdf.file_name IS '파일명';
COMMENT ON COLUMN resume.resume_pdf.generated_at IS 'PDF 생성일시';
-- ========================================
-- 인덱스
-- ========================================
CREATE INDEX idx_resume_user ON resume.resumes(user_id);
CREATE INDEX idx_profile_resume ON resume.resume_profile(resume_id);
CREATE INDEX idx_link_resume ON resume.resume_link(resume_id);
CREATE INDEX idx_exp_resume ON resume.resume_experience(resume_id);
CREATE INDEX idx_project_resume ON resume.resume_project(resume_id);
CREATE INDEX idx_edu_resume ON resume.resume_education(resume_id);
CREATE INDEX idx_skill_resume ON resume.resume_skill(resume_id);
CREATE INDEX idx_cert_resume ON resume.resume_certificate(resume_id);
CREATE INDEX idx_template_creator ON resume.templates(created_by);
CREATE INDEX idx_section_template ON resume.template_section(template_id);
CREATE INDEX idx_pdf_resume ON resume.resume_pdf(resume_id);
CREATE INDEX idx_pdf_template ON resume.resume_pdf(template_id);