spring.application.name=resume

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 기본 userDetailService 설정
spring.security.user.name=test
spring.security.user.password=test
spring.security.user.roles=ADMIN,USER

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG

# mybatis 설정
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.type-aliases-package=com.resume.core.dto

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
